"use client";

import { useActionState, useEffect, useState } from "react";
import { BriefcaseBusiness, DoorOpen, Plus, Stethoscope, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { saveProfessionalAction, saveRoomAction, saveServiceAction, saveSpecialtyAction, type CatalogState } from "@/app/professionals/actions";
import type { Professional, Room, Service, Specialty } from "@/lib/types";

type Section = "professionals" | "specialties" | "services" | "rooms";
const labels: Record<Section, string> = { professionals: "Profissionais", specialties: "Especialidades", services: "Serviços", rooms: "Salas" };
const initial: CatalogState = {};

function CatalogForm({ section, specialties }: { section: Section; specialties: Specialty[] }) {
  const router = useRouter(); const actionFor = { professionals: saveProfessionalAction, specialties: saveSpecialtyAction, services: saveServiceAction, rooms: saveRoomAction }[section]; const [state, action, pending] = useActionState(actionFor, initial);
  useEffect(() => { if (state.success) router.refresh(); }, [router, state.success]);
  return <form action={action} className="record-form">{section === "professionals" ? <><label>Nome completo<input name="name" required placeholder="Dra. Marina Costa"/></label><label>Especialidade<select name="specialtyId" required defaultValue=""><option value="" disabled>Selecione</option>{specialties.filter((item) => item.status === "ACTIVE").map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Registro profissional<input name="registration" required placeholder="CRM-SP 000000"/></label><label>Telefone<input name="phone" required/></label><label>E-mail<input name="email" type="email" required/></label></> : null}{section === "specialties" ? <label>Nome da especialidade<input name="name" required placeholder="Ex.: Pediatria"/></label> : null}{section === "services" ? <><label>Nome do serviço<input name="name" required placeholder="Ex.: Consulta"/></label><label>Duração (minutos)<input name="durationMinutes" type="number" min="5" defaultValue="30" required/></label><label>Valor (R$)<input name="price" type="number" min="0" step="0.01" required/></label></> : null}{section === "rooms" ? <><label>Nome da sala<input name="name" required placeholder="Ex.: Consultório 3"/></label><label>Descrição<input name="description" placeholder="Uso principal da sala"/></label></> : null}{state.error ? <p className="form-error">{state.error}</p> : null}{state.success ? <p className="success-message">{state.success}</p> : null}<button className="primary-button full" disabled={pending}>{pending ? "Salvando..." : `Salvar ${labels[section].slice(0,-1).toLowerCase()}`}</button></form>;
}

export function CatalogManager({ professionals, specialties, services, rooms }: { professionals: Professional[]; specialties: Specialty[]; services: Service[]; rooms: Room[] }) {
  const [section, setSection] = useState<Section>("professionals"); const [adding, setAdding] = useState(false); const records = { professionals, specialties, services, rooms }[section];
  const specialtyName = (id: string) => specialties.find((item) => item.id === id)?.name ?? "Especialidade";
  return <main className="directory-content"><header className="directory-header"><div><p className="eyebrow blue">CADASTROS</p><h1>Equipe e operação</h1><p>Profissionais, especialidades, serviços e salas da clínica.</p></div><button className="primary-button" onClick={() => setAdding(true)}><Plus size={16}/> Novo cadastro</button></header><div className="catalog-tabs" role="tablist">{(Object.keys(labels) as Section[]).map((item) => <button key={item} className={section === item ? "selected" : ""} onClick={() => setSection(item)} role="tab">{labels[item]} <span>{({professionals, specialties, services, rooms}[item]).length}</span></button>)}</div><section className="catalog-grid">{records.length ? records.map((record) => <article className="catalog-card" key={record.id}>{section === "professionals" ? <span className="person-avatar">{(record as Professional).name.split(" ").map((word) => word[0]).join("").slice(0,2)}</span> : <span className="catalog-icon">{section === "services" ? <BriefcaseBusiness size={18}/> : section === "rooms" ? <DoorOpen size={18}/> : <Stethoscope size={18}/>}</span>}<div><h2>{record.name}</h2>{section === "professionals" ? <p>{specialtyName((record as Professional).specialtyId)} · {(record as Professional).registration}</p> : null}{section === "services" ? <p>{(record as Service).durationMinutes} min · R$ {(record as Service).price.toFixed(2).replace(".", ",")}</p> : null}{section === "rooms" ? <p>{(record as Room).description || "Sem descrição"}</p> : null}{section === "specialties" ? <p>Especialidade ativa para agendamentos</p> : null}</div><em className={record.status === "ACTIVE" ? "status confirmed" : "status waiting"}>{record.status === "ACTIVE" ? "Ativo" : "Inativo"}</em></article>) : <div className="empty-state"><Stethoscope size={24}/><strong>Nenhum cadastro nesta seção</strong><p>Crie o primeiro item para começar.</p></div>}</section>{adding ? <div className="sheet-backdrop" role="dialog" aria-modal="true" aria-label={`Novo cadastro de ${labels[section]}`}><section className="form-sheet"><button className="close-button" onClick={() => setAdding(false)} aria-label="Fechar"><X size={18}/></button><p className="eyebrow blue">NOVO CADASTRO</p><h2>{labels[section]}</h2><p>Este cadastro fica disponível apenas para a Clínica Vida.</p><CatalogForm section={section} specialties={specialties}/></section></div> : null}</main>;
}
